### ISSUE TITLE
How do you show search

### ISSUE THREAD

**Issue by prosperva** [arcnovus/wet-booew-x#2]
Thanks for putting this together and once I have a hang of it, I will start contributing. One question, what is the best way to activate certain components, i.e. search under the language toggle.

Thanks

**Comment by prosperva** [comment]
Figured that you need to use `<DefaultTemplate>` component

**Comment by arcdev1** [comment]
> once I have a hang of it, I will start contributing

Would be much appreciated. Been short on time lately and would love some helping hands. 😅
